### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Radiergummi** [SeregPie/VueDragDrop#1]
I've tried using the demo, but while I can drag the symbols, dropping them on the users has no effect. I'm using a current Chrome on Windows RN.

**Comment by SeregPie** [comment]
Sorry. This plugin is still not ready. I needed this for my project at the work. Later I realised that I only need the DragItem and not DropArea. So it's on hold right now.

**Comment by Radiergummi** [comment]
Let me know if you'd like some help with it, I need this for a work project too and the API feels way better than the alternatives, so I'd definitely be willing to put some time into it.
